# Usa una imagen de Maven para compilar la aplicación
FROM maven:3.8.4-openjdk-17 AS build

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia el archivo POM y el código fuente
COPY pom.xml .
COPY src ./src

# Compila la aplicación sin ejecutar los tests
RUN mvn package -DskipTests

# Crea una imagen de OpenJDK 17 como base para la aplicación
FROM openjdk:17-jdk-slim

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia el archivo JAR generado en la etapa anterior
COPY --from=build /app/target/resource-server-0.0.1-SNAPSHOT.jar .

# Expone el puerto 8080 (o el puerto que uses en tu aplicación)
EXPOSE 8080

# Ejecuta la aplicación cuando el contenedor se inicie
CMD ["java", "-jar", "resource-server-0.0.1-SNAPSHOT.jar"]
